apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  title: ${{ values.name | title }} AI Agent
  description: ${{ values.description }}
  tags:
    - ai
    - langchain
    - kafka
    - python
    - monitoring
    - notifications
  annotations:
    argocd/app-selector: backstage.io/app=${{values.name}}
    backstage.io/kubernetes-id: ${{values.name}}
    backstage.io/source-location: url:https://${{values.host}}/${{values.owner}}/${{values.destination}}
    github.com/project-slug: ${{values.owner}}/${{values.destination}}
    github.com/workflows: build.yaml
  links:
    - url: https://devspaces${{values.cluster}}/#https://${{values.host}}/${{values.owner}}/${{values.destination}}
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: https://devspacesapps${{values.cluster}}/#https://${{values.host}}/${{values.owner}}/${{values.destination}}?che-editor=che-incubator/che-idea/latest
      title: OpenShift Dev Spaces (JetBrains IntelliJ)
      icon: web
spec:
  type: service
  lifecycle: experimental
  owner: ${{ values.catalog_owner }}
  system: ${{ values.system }}
  dependsOn:
    - resource:kafka-message-broker
    - ${{ values.monitoredTopic }}
    - resource:openai-service
  providesApis: []
  consumesApis: [] 
